netwars_beat:
  build: .
  environment:
    - PYTHONPATH=/etc/netwars:$PATH
  volumes:
    - .:/etc/netwars
  links:
    - redis

  command: ['python','nw/beat.py']

netwars_scrape:
  build: .
  environment:
    - PYTHONPATH=/etc/netwars:$PATH
  volumes:
    - .:/etc/netwars
#  command: ['python','parse_raw_nw.py']
#
#
#workers:
#  build: .
#  links:
#    - redis

redis:
    image: redis
    ports:
      - '6379:6379'

